inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'exe/**/*'
    - 'examples/**/*'
    - 'docs/**/*'

Layout/LineLength:
  Max: 150

Style/RedundantHeredocDelimiterQuotes:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false



Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Security/Eval:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ReturnNil:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false
