# Scarpe App Bootstrap — generated by scarpe package
ENV['SCARPE_DISPLAY'] ||= 'wv_local'

# Suppress CHANGELOG.md warning in packaged mode
ENV['SCARPE_PACKAGED'] = '1'

# In packaged mode, some optional gem dependencies may not be present
# (e.g., nokogiri, sqlite3, fastimage are only loaded when actually used).
# Relax RubyGems dependency checking so Scarpe can activate without them.
module Gem
  class Specification
    alias_method :_packaged_activate_deps, :activate_dependencies
    def activate_dependencies
      _packaged_activate_deps
    rescue Gem::MissingSpecError
      # Optional dependency not present in bundle — acceptable
    end
  end
end

require 'scarpe'
require 'scarpe/wv'

app_file = ARGV[0] || raise("No app file specified!")
Shoes.run_app(app_file)
