#!/usr/bin/env ruby
# frozen_string_literal: true

# Writes spec/examples.yml: one line per example under examples/.
#
# category and needs come from native/research/examples_inventory.json. status and reason
# are seeded once from the research baseline (native/research/niente_baseline.json) and are
# hand-maintained after that: a rerun keeps every existing entry's status, reason, steps, wait,
# dialogs, pixels and ruby, adds new examples as `loads`, and drops examples that no longer exist.
#
#   ruby spec/generate_examples_yml.rb

require "json"
require "yaml"

REPO = File.expand_path("..", __dir__)
OUT = File.join(__dir__, "examples.yml")
INVENTORY = File.join(REPO, "native", "research", "examples_inventory.json")
BASELINE = File.join(REPO, "native", "research", "niente_baseline.json")
KEPT_FIELDS = %w[status reason steps wait dialogs pixels ruby].freeze

HEADER = <<~YAML
  # Every example under examples/, smoke-run by `spec/run --examples` (see spec/README.md).
  #
  # status:  loads  must load and run without a Ruby error (native: and render a non-blank frame)
  #          fails  known broken; reason says why; a clean run reports unexpected_pass
  #          skip   not run: side effects, network, missing gems, Shoes 3 only
  #          or a Hash by display, e.g. {niente: loads, native: fails}
  # reason:  why an example fails or is skipped
  # steps:   native only, passed to `scarpe peek` in order: [{click: "OK"}, {type: "hi"}, {key: "return"}]
  # dialogs: answers for the example's dialogs, both displays: {confirm: true, ask_color: "#f80"}
  # ruby:    the Rubies the status holds on, e.g. ">= 4.0"; on any other Ruby the example must load
  # wait:    seconds to run it (default 3 niente, 1.5 native)
  #
  # category and needs are regenerated by spec/generate_examples_yml.rb; the rest is hand-kept.
YAML

def seed_status(row, baseline)
  path, category, needs = row.values_at("path", "category", "needs")
  result = baseline[path] || {}
  first_error = result["first_error"].to_s.sub(%r{\A.*?(examples/|lacci/)}, '\1').sub(%r{\A/\S*/}, "").strip[0, 240]

  case
  when category.start_with?("legacy/shoes3_only") then ["skip", "Shoes 3 only (examples/legacy/shoes3_only/README.md)"]
  when category.start_with?("legacy/path_issues") then ["skip", "needs files that are not in the repo (examples/legacy/path_issues/README.md)"]
  when category.start_with?("legacy/needs_deps") then ["skip", "needs gems we do not ship (examples/legacy/needs_deps/README.md)"]
  when needs.any? { |need| need.start_with?("gem:bloops") } || category.start_with?("bloopsaphone")
    ["skip", "needs the bloops audio gem"]
  when result["status"] == "not_run" then ["skip", result["first_error"].to_s.sub("not run: ", "")]
  when result["status"] == "hung_killed" then ["skip", "never exits: runs a server"]
  when needs.include?("network:download") || needs.include?("network:net_http") then ["skip", "fetches from the network"]
  when %w[fail loads_with_errors].include?(result["status"]) then ["fails", first_error]
  else ["loads", nil]
  end
end

def line_for(path, fields)
  pairs = fields.map { |key, value| "#{key}: #{JSON.generate(value)}" }
  "#{JSON.generate(path)}: {#{pairs.join(", ")}}"
end

# Examples added since the research inventory get a row with no known needs.
def with_new_examples(inventory)
  known = inventory.map { |row| row["path"] }
  added = Dir.chdir(REPO) { Dir.glob("examples/**/*.rb") } - known
  inventory + added.map do |path|
    { "path" => path, "category" => File.dirname(path).delete_prefix("examples").delete_prefix("/").then { |dir| dir.empty? ? "." : dir }, "needs" => [] }
  end
end

inventory = with_new_examples(JSON.parse(File.read(INVENTORY)))
baseline = JSON.parse(File.read(BASELINE)).to_h { |row| [row["path"], row] }
existing = File.exist?(OUT) ? (YAML.safe_load_file(OUT) || {}) : {}

lines = inventory.sort_by { |row| row["path"] }.filter_map do |row|
  path = row["path"]
  next unless File.exist?(File.join(REPO, path))

  kept = existing.fetch(path, {}).slice(*KEPT_FIELDS)
  status, reason = seed_status(row, baseline)
  fields = { "category" => row["category"], "needs" => row["needs"] }
  fields.merge!(kept.empty? ? { "status" => status, "reason" => reason }.compact : kept)
  line_for(path, fields)
end

File.write(OUT, HEADER + "\n" + lines.join("\n") + "\n")
counts = YAML.safe_load_file(OUT).values.map { |fields| fields["status"].to_s }.tally
puts "wrote #{OUT}: #{lines.size} examples #{counts}"
