# Boot script for packaged Scarpe app (Linux)
# Auto-generated by scarpe package

# Relax dependency checking for packaged apps
module Gem
  class Specification
    alias_method :_packaged_activate_deps, :activate_dependencies
    def activate_dependencies
      _packaged_activate_deps
    rescue Gem::MissingSpecError
      # Optional dependency not present in bundle
    end
  end
end

# Suppress changelog warning
ENV["SCARPE_SILENCE_CHANGELOG"] = "1"
ENV["SCARPE_DISPLAY"] = "wv_local"

require "scarpe"
require "scarpe/wv"

# Load and run the app
load File.join(__dir__, "main.rb")
