#!/usr/bin/env ruby

use_dev = ARGV.delete("--dev") ? true : false

if ARGV.length != 1
    puts <<USAGE
Usage: scarpe [OPTIONS] <scarpe app file>
  Options:
      --dev                          Use development local scarpe, not an installed gem
USAGE
    exit -1
end

if use_dev
    dev_path = File.expand_path("../lib", __dir__)
    $LOAD_PATH.prepend dev_path
end

require "scarpe"

Shoes = Scarpe unless defined?(Shoes)

# Run the Scarpe app file
load ARGV[0]
